#!/bin/bash


# Function to display help information
display_help() {
    echo "Look: vi me_replacer"
}

# Initialize variables for source and output files
source_file=""
output_file=""

# Parse options
while getopts "S:O:H" opt; do
 case ${opt} in
    S)
      source_file="$OPTARG"
      ;;
    O)
      output_file="$OPTARG"
      ;;
    H)
      display_help
      exit 0
      ;;

    \?)
      echo "WRONG Do -H for help: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
 esac
done

# Check if source file is provided
if [ -z "$source_file" ]; then
 echo "Type -H for help"
 exit 1
fi

# Check if output file is provided
if [ -z "$output_file" ]; then
 echo "FATAL CRESCH"
 exit 1
fi

# Get the size of the original file
file_size=$(stat -c%s "$source_file")

# Create a new file filled with zeros, with the same size as the original file
dd if=/dev/zero of="$output_file" bs=1 count=$file_size

echo "Freetarded IME has been created at $output_file"


#This code has been generated by urg.ai
